### ISSUE TITLE
Error: Cannot add a Service with the same UUID without defining a unique ‘subtype’ property

### ISSUE THREAD

**Issue by samunderwood** [danieljtribe/homebridge-agile-octopus#20]
I'm encountering an issue with the Homebridge Agile Octopus plugin. After restarting Homebridge, the following error is displayed in the logs:

```
[11/09/2024, 21:52:14] Error: Cannot add a Service with the same UUID '00000049-0000-1000-8000-0026BB765291' as another Service in this Accessory without also defining a unique 'subtype' property.
    at Accessory.addService (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:556:17)
    at PlatformAccessory.addService (/var/lib/homebridge/node_modules/homebridge/src/platformAccessory.ts:99:41)
    at /var/lib/homebridge/node_modules/homebridge-agile-octopus-rates/src/platformAccessory.ts:62:227
    at Array.forEach (<anonymous>)
    at AgileOctopusAccessory.init (/var/lib/homebridge/node_modules/homebridge-agile-octopus-rates/src/platformAccessory.ts:61:30)
    at new AgileOctopusAccessory (/var/lib/homebridge/node_modules/homebridge-agile-octopus-rates/src/platformAccessory.ts:47:10)
    at AgileOctopusPlatform.discoverDevices (/var/lib/homebridge/node_modules/homebridge-agile-octopus-rates/src/platform.ts:40:9)
    at HomebridgeAPI.<anonymous> (/var/lib/homebridge/node_modules/homebridge-agile-octopus-rates/src/platform.ts:19:12)
    at HomebridgeAPI.emit (node:events:531:35)
    at HomebridgeAPI.signalFinished (/var/lib/homebridge/node_modules/homebridge/src/api.ts:275:10)
```

It seems the plugin is trying to add a service with a duplicate UUID without specifying a unique `subtype`, which is causing a conflict.

### Steps to reproduce:
1. Install the Homebridge Agile Octopus plugin.
2. Start Homebridge.
3. Observe the error in the logs after Homebridge attempts to initialize the plugin.

### Environment:
- **Homebridge Version**: 1.8.4
- **Node.js Version**: v20.17.0
- **Plugin Version**: 1.2.4

**Comment by danieljtribe** [comment]
Hi @samunderwood ,

Thank you for your bug report, I've had a look this morning and have been able to replicate this issue when defining a custom device in the config without defining a `name` attribute, I will patch this problem. Though from the replication steps provided it sounds like you had a new install of the plugin without a config of this type so may be experiencing a slightly different problem.

Would it be okay to have a copy of your config for this plugin so I could run this in debug here? 

Many thanks,
Dan

**Comment by samunderwood** [comment]
Hey @danieljtribe! I found the same thing. I'm not 100% sure if an empty custom config was added by default when I installed it or if I added it and forgot to delete it. When I deleted it, the issue was fixed.

I made it before I saw your message, so I'm unsure if the configuration will still be useful.

**Comment by danieljtribe** [comment]
Thanks @samunderwood , I think that’s exactly what it was, it looks like when using the Homebridge UI it creates a blank custom device with empty values for all of the values. 
I’ve added handing for this in the latest update to ignore any un-configured custom devices. 

Thanks again for your report of this issue! Please don’t hesitate to let me know this issue if this comes up again or if you have any other queries or suggestions for this plugin! 

Dan
